name: Fast_learning
description: A new Flutter project.

# C:\Android_Flutter\flutter_windows_2.5.3-stable\flutter\bin\flutter
# C:\Android_Flutter\flutter_windows_2.5.3-stable\flutter\bin\flutter build apk --split-per-abi 
# git archive --format zip --output ./project.zip main
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.1.23+23

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  
  flutter:
    sdk: flutter
  syncfusion_flutter_sliders: ^20.4.53
  percent_indicator: ^4.2.3
  dotted_border: ^2.0.0+3
  url_launcher: any
  liquid_progress_indicator: ^0.4.0
  dio: ^4.0.6
  async: ^2.9.0
  path_provider: any
  showcaseview: ^1.1.8
  is_lock_screen: ^2.0.0
  get: ^4.1.4  
  auto_size_text: ^3.0.0
  # get: any
  #add be awake functionality
  wakelock: any
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_datetime_picker: ^1.5.1
  intl: ^0.17.0
  http: ^0.13.5
  chewie: ^1.2.2
  video_player: ^2.1.12
  flutter_local_notifications: ^13.0.0
  flutter_native_timezone: ^1.1.0
  rxdart: ^0.27.1
  # sqflite_sqlcipher: ^2.0.0
  sqfentity: ^2.3.0+5
  sqfentity_gen: ^2.3.0+4
  get_storage: ^2.0.3
  bubble_tab_indicator: ^0.1.6
  syncfusion_flutter_pdfviewer: ^20.3.49
  just_audio: ^0.9.5
  persistent_bottom_nav_bar: ^5.0.2
  image_picker: ^0.8.4
  group_radio_button: ^1.1.0
  record: ^3.0.0
  # flutter_sound: ^8.1.9
  permission_handler: ^10.1.0
  path: ^1.8.0
  # sound_stream: ^0.3.0
  # record_mp3: ^3.0.0
  uuid: ^3.0.4
  shamsi_date: ^1.0.1
  text_to_speech: ^0.2.3
  badges: ^2.0.1
  flip_card: ^0.6.0
  assets_audio_player: ^3.0.3+6
  easy_folder_picker: ^1.1.1
  file_picker: ^5.2.1
  filesystem_picker: ^3.1.0
  flutter_archive: ^5.0.0
  shared_preferences: ^2.0.7
  share: ^2.0.4
  darq: ^1.1.1
  encrypt: ^5.0.1
  archive: ^3.1.6
  workmanager: ^0.5.0
  analyzer: ^4.7.0
  flutter_quill: ^6.0.8+1
  purchases_flutter: ^4.2.1
  firebase_messaging: ^14.2.1
  firebase_core: ^2.4.1
  photo_view: ^0.14.0
  # flutter_tts: ^3.2.2
  youtube_player_flutter: ^8.1.2
  youtube_player_iframe: ^4.0.4

dependency_overrides:
  image_picker_android: 0.8.5+3
dev_dependencies:  
  build_runner: ^2.3.0
  build_verify: ^3.0.0
  flutter_launcher_icons: ^0.10.0
# dependency_overrides:
#   analyzer: '1.5.0'
flutter_icons:
  android: true 
  ios: true
  image_path: "assets/images/icon.png"
  remove_alpha_ios: true
  adaptive_icon_foreground: "assets/images/android_icon.png"
  adaptive_icon_background: "#ffffff"
  min_sdk_android: 23
  
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

    # - assets/video/
    - assets/zip/
    # - assets/pdf/
    - assets/music/
 

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: IRANSansMobile(FaNum)
      fonts:    
        - asset: fonts/IRANSansMobile(FaNum).ttf
    - family: IRANSansMobile
      fonts:    
        - asset: fonts/IRANSansMobile.ttf      
    - family: Dana
      fonts:    
        - asset: fonts/Dana.ttf
    - family: Vazir
      fonts:    
        - asset: fonts/Vazir.ttf        
    - family: Sans
      fonts:    
        - asset: fonts/OpenSans-Regular.ttf    
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
