// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpCllKaeg3YDGl9gTHv3BOB0sMPkiOHbE',
    appId: '1:1028007756666:web:5285760527a39f9240ccc3',
    messagingSenderId: '1028007756666',
    projectId: 'fast-learning-firebase',
    authDomain: 'fast-learning-firebase.firebaseapp.com',
    storageBucket: 'fast-learning-firebase.appspot.com',
    measurementId: 'G-RVDMV8GBGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1LI3MZxVj3E76bCtdoIoEJ8tdK1MQKB8',
    appId: '1:1028007756666:android:8e41d5907c3e3d7a40ccc3',
    messagingSenderId: '1028007756666',
    projectId: 'fast-learning-firebase',
    storageBucket: 'fast-learning-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhU5AY0Qi8n4yFe6y6RimdVaS-ST9ZJbA',
    appId: '1:1028007756666:ios:2992feea75e3933140ccc3',
    messagingSenderId: '1028007756666',
    projectId: 'fast-learning-firebase',
    storageBucket: 'fast-learning-firebase.appspot.com',
    iosClientId:
        '1028007756666-niha28frll37i58ibnqhro4sp6gscku0.apps.googleusercontent.com',
    iosBundleId: 'com.drehsani.Fast.learning',
  );
}
